TicketsApplication/src/TicketsApplication/Controllers/TicketController.cs
using AutoMapper;
using BLL.DTO;
using BLL.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TicketsApplication.Models;

namespace TicketsApplication.Controllers
{
    [Authorize]
    public class TicketController : Controller
    {
            ITicketService ts;
            IUserInfo us;

            public TicketController(ITicketService ts, IUserInfo us)
            {
                this.ts = ts;
                this.us = us;
            }
        #region level1 Отпрака собственных билетов на продажу
        public IActionResult TicketsStart()
        {
            List<TicketVM> model = Mapper.Map<List<TicketVM>>(ts.TicketStart(us.GetUser(User.Identity.Name)));
            return View(model);
        }

        [HttpPost]
        public IActionResult ticketForSale(List<TicketVM> model)
        {
            List<TicketVM> result = new List<TicketVM>();
            foreach (var i in model)
            {
                if (i.Availability)
                    result.Add(i);
            }
            ts.update_tickets(Mapper.Map<List<TicketDTO>>(result));
            return RedirectToAction("TicketsStart");
        }
        #endregion

        #region level2 продающиеся билеты
        [AllowAnonymous]
        public IActionResult Tickets(int id)
        {
            TicketCountVM tcvm = new TicketCountVM();
            tcvm.PriceAndCount = Mapper.Map<ICollection<KeyValuePair<decimal, int>>>(ts.GetTicketCountDTO(id));
            EventDTO ev = ts.GetEventForTicket(id);
            tcvm.Event = Mapper.Map<EventVM>(ev);
            return View(tcvm);
        }

        #endregion

        #region level3 покупка
        public IActionResult TicketsForOrder(decimal price, int eventId)
        {
            List<TicketDTO> tdto = ts.TicketsForEvent(eventId, price);
            List<TicketVM> tickets = Mapper.Map<List<TicketVM>>(tdto);
            return View(tickets);
        }

        public IActionResult Buy(List<TicketVM> models)
        {
            int userID = us.GetUser(User.Identity.Name).ID;
            List<TicketVM> result = new List<TicketVM>();
            foreach (var i in models)
            {
                if (i.ForSale)
                {
                    i.BuyerID = userID;
                    i.Availability = false;
                    result.Add(i);
                }
            }
            ts.buy_tickets(Mapper.Map<List<TicketDTO>>(result));
            return RedirectToAction("UserOrders");
        }

        #endregion

        #region level4 заказы у пользователя

        public IActionResult UserTickets()
        {
            List<TicketVM> tickets = Mapper
                .Map<List<TicketVM>>(ts.TicketsForUser(us.GetUser(User.Identity.Name)));
            return View(tickets);
        }

        [HttpPost]
        public IActionResult change_order_status(List<TicketVM> model)
        {
            if (model.Count != 0)
            {
                foreach(var i in model)
                {
                    if (i.OrderStatus == "sold")
                    {
                        ts.update_order_info(i.ID, 2, i.AnswerText, i.SellerID, i.BuyerID);
                    }
                    if (i.OrderStatus == "reject")
                    {
                        ts.update_order_info(i.ID, 3, i.AnswerText);
                    }
                }
            }
            return RedirectToAction("UserTickets");
        }
        #endregion

        public IActionResult UserOrders()
            {
                List<TicketVM> tickets = Mapper
                .Map<List<TicketVM>>(ts.TicketOrderUser(us.GetUser(User.Identity.Name)));
                return View(tickets);
            }
    }
}

TicketsApplication/src/TicketsApplication/Controllers/UserController.cs
using AutoMapper;
using BLL.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TicketsApplication.Models;
using Microsoft.AspNetCore.Identity;
using System.Security.Principal;
using System.Security.Claims;

namespace TicketsApplication.Controllers
{
    public class UserController : Controller
    {
        IUserInfo us;
        IAccount accServ;
        public UserController(IUserInfo us, IAccount accServ)
        {
            this.us = us;
            this.accServ = accServ;
        }

        public IActionResult UserInformation(string nick)
        {
            UserVM user = Mapper.Map<UserVM>(us.GetUser(nick));
            return View(user);
        }
        public IActionResult AccountOptions()
        {
            UserVM user = Mapper.Map<UserVM>(us.GetUser(User.Identity.Name));
            return View(user);
        }

      
        public IActionResult changeAddress()
        {
            return PartialView();
        }
        public IActionResult changePhone()
        {
            return PartialView();
        }
        [HttpPost]
        public IActionResult changePhone(string newPhone)
        {
            if (newPhone != null)
            {
                us.change_phone(User.Identity.Name, newPhone);
            }
            return RedirectToAction("AccountOptions");
        }
        [HttpPost]
        public IActionResult changeAddress(string newAddress)
        {
            if (newAddress != null)
            {
                us.change_address(User.Identity.Name, newAddress);
            }
            return RedirectToAction("AccountOptions");
        }
   
        public IActionResult changePassword()
        {
            return PartialView();
        }
        [HttpPost]
        public IActionResult changePassword(string newPassword)
        {
            if (newPassword != null)
            {
                us.change_password(User.Identity.Name, newPassword);
            }
          
            return RedirectToAction("AccountOptions");
        }

        private async Task Authenticate(string userNick)
        {
            var claims = new List<Claim>
                   {
                        new Claim(ClaimsIdentity.DefaultNameClaimType, userNick),
                        new Claim(ClaimsIdentity.DefaultRoleClaimType, accServ.GetRoleNameForUserNick(userNick))
                   };

            ClaimsIdentity id = new ClaimsIdentity(claims, "ApplicationCookie", ClaimsIdentity.DefaultNameClaimType,
                ClaimsIdentity.DefaultRoleClaimType);
            await HttpContext.Authentication.SignInAsync("Cookies", new ClaimsPrincipal(id));
        }

    }
}

TicketsApplication/src/TicketsApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="~/css/style.css" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <title>Tickets Resailing</title>
 
</head>
<body>
   
    <div class="wrapper">     
        <header>
            <img class="logo" src="~/images/Logo.png" height="100" />
            <div class="pHeader">
                <p class="headerText">@Localizer["Address: Gomel, Pushkina 5"]</p>
                <p class="headerText">@Localizer["Tel: 232-32-32"]</p>
            </div>
            <div class="user">
            @if (User.Identity.IsAuthenticated)
            {
               <span>@User.Identity.Name</span> 
            }
            else
            {
                <span>Guest</span>
            }
           </div>
        </header>
        <div id="menu">
            @if (User.Identity.IsAuthenticated)
            {
                <ul>
                    <li><a asp-controller="User" asp-action="AccountOptions">@Localizer["My account"]</a></li>
                    <li><a asp-controller="Home" asp-action="Index">@Localizer["Home"]</a></li>
                    <li><a asp-controller="Ticket" asp-action="UserTickets">@Localizer["By ​​tickets"]</a></li>
                    <li><a asp-controller="Ticket" asp-action="UserOrders">@Localizer["My Orders"]</a></li>
                    <li><a asp-controller="Ticket" asp-action="TicketsStart">@Localizer["My Tickets"]</a></li>
                    <li><a asp-controller="Account" asp-action="Logout">@Localizer["Logout"]</a></li>
                    @if (User.IsInRole("Admin"))
                    {
                        <li><a asp-controller="Admin" asp-action="AdminOptions">@Localizer["Admin options"]</a></li>
                        <li><a asp-controller="Admin" asp-action="optionAddOrDeleteAdmin">@Localizer["Option to add admin"]</a></li>
                    }
                </ul>

            }
            else
            {
                <ul>
                    <li><a asp-controller="Home" asp-action="Index">@Localizer["Home"]</a></li>
                    <li><a asp-controller="Account" asp-action="Login">@Localizer["Login"]</a></li>
                    <li><a asp-controller="Account" asp-action="Register">@Localizer["Register"]</a></li>
                </ul>
            }
        </div>

        <div class="content">
            @RenderBody()
        </div>
             <div class="footer">                 
                
                 @RenderSection("Footer", false)

             </div>
       
    </div>
    
</body>
</html>

TicketsApplication/src/TicketsApplication/Views/Shared/_SelectLanguagePartial.cshtml
@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
}
<div title="@Localizer["Request culture provider:"] @requestCulture?.Provider?.GetType().Name">
    <form id="selectLanguage" asp-controller="Home"
          asp-action="SetLanguage" asp-route-returnUrl="@Context.Request.Path"
          method="post" class="form-horizontal" role="form">
        @Localizer["Language:"] <select name="culture"
                                        asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems"></select>
        <button type="submit" class="button">Save</button>
    </form>
</div>