TicketsApplication/src/TicketsApplication/Controllers/EventOptionsController.cs
using AutoMapper;
using BLL.DTO;
using BLL.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using TicketsApplication.Models;

namespace TicketsApplication.Controllers
{
    [Authorize(Roles = "Admin")]
    public class EventOptionsController : Controller
    {
        IHostingEnvironment env;
        IEventOption serv;

        public EventOptionsController(IHostingEnvironment env, IEventOption serv)
        {
            this.env = env;
            this.serv = serv;
        }

        #region createEvent

        [HttpGet]
        public IActionResult create_event()
        {
            EventVM model = new EventVM();
            model.Date = DateTime.Now;
            int selectedIndex = 1;
            model.Cities = Mapper.Map<List<CityVM>>(serv.GetCities());
            SelectList cities = new SelectList(model.Cities, "ID", "Name", selectedIndex);
            ViewBag.Cities = cities;
            model.Venues = Mapper.Map<List<VenueVM>>(serv.GetVenues());
            SelectList venues = new SelectList(model.Venues.Where(c => c.CityID == selectedIndex), "ID", "Name");
            ViewBag.Venues = venues;
            return View(model);
        }

        [HttpGet]
        public PartialViewResult GetVenues(int id)
        {
            return PartialView(serv.GetVenues().Where(c => c.CityID == id).ToList());
        }

        [HttpPost]
        public IActionResult create_event(EventVM model, IFormFile downloadableFile, int countTickets)
        {
            if (ModelState.IsValid)
            {
                if (model.Date > DateTime.Now)
                {
                    if (downloadableFile != null)
                    {
                        using (var fileStream = new FileStream(env.WebRootPath + "/images/" + downloadableFile.FileName, FileMode.Create))
                        {
                            downloadableFile.CopyTo(fileStream);
                        }
                        model.Banner = "images/" + downloadableFile.FileName;
                    }
                    serv.add_event(Mapper.Map<EventDTO>(model));
                    int eventID = serv.GetIDLastEvent();
                    serv.add_tickets(countTickets, eventID);
                }
                else
                {
                    return RedirectToAction("createEvent");
                }
            }
            else
            {
                return RedirectToAction("createEvent");
            }

            return RedirectToAction("Index", "Home");
        }

        #endregion

        #region deleteEvent

        [HttpGet]
        public IActionResult delete_event()
        {
            return View(DataSelection());
        }

        [HttpPost]
        public IActionResult delete_event(EventVM model)
        {
            if (model.ID != 0)
            {
                string path1 = serv.Banner(model.ID);
                string path2 = env.WebRootPath + "/" + path1;
                string path = path2.Replace("/", @"\");
                try
                {
                    System.IO.File.Delete(path);
                }
                catch
                { }

                serv.delete_event(model.ID);
            }
            return RedirectToAction("Index", "Home");
        }
        #endregion

        #region updateEvent

        [HttpGet]
        public IActionResult update_event()
        {
            return View(DataSelection());
        }

        [HttpPost]
        public IActionResult update_event_action(int id)
        {
            EventUpdateVM vm = Mapper.Map<EventUpdateVM>(serv.GetEvent(id));
            int selectedIndex = vm.CityID;
            vm.Cities = Mapper.Map<List<CityVM>>(serv.GetCities());
            SelectList cities = new SelectList(vm.Cities, "ID", "Name", selectedIndex);
            ViewBag.Cities = cities;
            vm.Venues = Mapper.Map<List<VenueVM>>(serv.GetVenues());
            SelectList venues = new SelectList(vm.Venues.Where(c => c.CityID == selectedIndex), "ID", "Name");
            ViewBag.Venues = venues;
            return View(vm);
        }
        [HttpPost]
        public IActionResult update_event_result(EventUpdateVM model)
        {

            EventUpdateVM oldModel = Mapper.Map<EventUpdateVM>(serv.GetEvent(model.ID));
            if (ModelState.IsValid)
            {
                model.Banner = oldModel.Banner;
                model.Date = oldModel.Date;
                if (model.Name == null)
                    model.Name = oldModel.Name;
                if (model.Description == null)
                    model.Description = oldModel.Description;

                serv.update_event(Mapper.Map<EventDTO>(model));
                return RedirectToAction("Index", "Home");
            }
            else
                return RedirectToAction("update_event_result");
        }
        #endregion

        [HttpGet]
        public PartialViewResult GetEvents(int id)
        {
            return PartialView(serv.GetEvents(id));
        }

        private EventVM DataSelection()
        {
            EventVM model = new EventVM();
            int selectedIndex = 1;
            List<CityVM> cities = Mapper.Map<List<CityVM>>(serv.GetCities());
            SelectList citiesDD = new SelectList(cities, "ID", "Name", selectedIndex);
            List<EventVM> events = Mapper.Map<List<EventVM>>(serv.GetEvents(selectedIndex));
            SelectList eventsDD = new SelectList(events, "ID", "Name");
            ViewBag.Cities = cities;
            ViewBag.Events = events;
            return model;
        }
    }
}

TicketsApplication/src/TicketsApplication/Controllers/VenueOptionsController.cs
using AutoMapper;
using BLL.DTO;
using BLL.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TicketsApplication.Models;

namespace TicketsApplication.Controllers
{
    public class VenueOptionsController : Controller
    {
        IVenueOptions serv;

        public VenueOptionsController(IVenueOptions serv)
        {
            this.serv = serv;
        }

        #region createVenue

        [HttpGet]
        public IActionResult create_venue()
        {
            int selectedIndex = 1;
            List<CityVM> cities = Mapper.Map<List<CityVM>>(serv.GetCities());
            SelectList citiesDD = new SelectList(cities, "ID", "Name", selectedIndex);
            ViewBag.Cities = cities;
            return View();
        }
        [HttpPost]
        public IActionResult create_venue(VenueVM model)
        {
            if (ModelState.IsValid)
            {
                serv.create_venue(Mapper.Map<VenueDTO>(model));
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("createVenue");
        }
        #endregion

        #region deleteVenue
        [HttpGet]
        public IActionResult delete_venue()
        {
            int selectedIndex = 1;
            List<CityVM> cityL = Mapper.Map<List<CityVM>>(serv.GetCities());
            SelectList cities = new SelectList(cityL, "ID", "Name", selectedIndex);
            ViewBag.Cities = cities;
            List<VenueVM> venuesL = Mapper.Map<List<VenueVM>>(serv.GetVenues());
            SelectList venues = new SelectList(venuesL.Where(c => c.CityID == selectedIndex), "ID", "Name");
            ViewBag.Venues = venues;
            return View();
        }
        [HttpPost]
        public IActionResult delete_venue(VenueVM model)
        {
            if (model != null && model.ID != 0)
            {
                serv.delete_venue(model.ID);
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("deleteVenue");
        }
        #endregion

        #region updateVenue
        [HttpGet]
        public IActionResult update_venue()
        {
            int selectedIndex = 1;
            List<CityVM> cityL = Mapper.Map<List<CityVM>>(serv.GetCities());
            SelectList cities = new SelectList(cityL, "ID", "Name", selectedIndex);
            ViewBag.Cities = cities;
            List<VenueVM> venuesL = Mapper.Map<List<VenueVM>>(serv.GetVenues());
            SelectList venues = new SelectList(venuesL.Where(c => c.CityID == selectedIndex), "ID", "Name");
            ViewBag.Venues = venues;
            return View();
        }

        [HttpGet]
        public PartialViewResult GetVenues(int id)
        {
            return PartialView(serv.GetVenues().Where(c => c.CityID == id).ToList());
        }

        [HttpGet]
        public PartialViewResult VenuesGet(int id)
        {
            return PartialView(serv.GetVenues().Where(c => c.CityID == id).ToList());
        }
        [HttpPost]
        public IActionResult update_venue_action(int id)
        {
            VenueVM vm = Mapper.Map<VenueVM>(serv.GetVenue(id));
            return View(vm);

        }

        [HttpPost]
        public IActionResult update_venue_result(VenueVM model)
        {
            if (ModelState.IsValid)
            {
                serv.update_venue(Mapper.Map<VenueDTO>(model));
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("updateVenueResult");
        }
        #endregion
    }
}

TicketsApplication/src/TicketsApplication/Views/Admin/AdminOptions.cshtml
<table border="1">
    <tr>
        <th>@Localizer["Events"]</th>
        <th><a asp-controller="EventOptions" asp-action="create_event">@Localizer["Create"]</a></th>        
        <th><a asp-controller="EventOptions" asp-action="update_event">@Localizer["Update"]</a></th>
        <th><a asp-controller="EventOptions" asp-action="delete_event">@Localizer["Delete"]</a></th>
    </tr>
    <tr>
        <th>@Localizer["Venues"]</th>
        <th><a asp-controller="VenueOptions" asp-action="create_venue">@Localizer["Create"]</a></th>
        <th><a asp-controller="VenueOptions" asp-action="update_venue">@Localizer["Update"]</a></th>
        <th><a asp-controller="VenueOptions" asp-action="delete_venue">@Localizer["Delete"]</a></th>
    </tr>
    <tr>
        <th>@Localizer["Cities"]</th>
        <th><a asp-controller="Cities" asp-action="create_city">@Localizer["Create"]</a></th>
        <th><a asp-controller="Cities" asp-action="update_city">@Localizer["Update"]</a></th>
        <th><a asp-controller="Cities" asp-action="delete_city">@Localizer["Delete"]</a></th>
    </tr>
 </table>
    @section Footer {
        ticket@ticket.by
    }

TicketsApplication/src/TicketsApplication/Views/Admin/GetAdmins.cshtml
<select id="user" name="ID">
    @foreach (var i in ViewBag.Users)
    {
        <option value="@i.ID">@i.Nick</option>
    }
</select>
           

TicketsApplication/src/TicketsApplication/Views/Admin/GetUsers.cshtml
<select id="user" name="ID">
    @foreach (var i in ViewBag.Users)
    {
        <option value="@i.ID">@i.Nick</option>
    }
</select>
                

TicketsApplication/src/TicketsApplication/Views/Admin/optionAddOrDeleteAdmin.cshtml
@model UserVM
@using (Html.BeginForm("optionAddOrDeleteAdmin", "Admin", FormMethod.Post))
{
    <fieldset>
        <legend>@Localizer["Change role"]</legend>
        <span>@Localizer["Assign admin"] </span> <input type="radio" id="forAdmin" name="users" checked/><br />
        <span>@Localizer["Remove the admin"] </span> <input type="radio" id="forUser" name="users"/><br />
     
            <div class="editor-field">
                <select id="user" name="ID">
                    @foreach (var i in ViewBag.Users)
                   {
                        <option value="@i.ID">@i.Nick</option>
                    }
                </select>
            </div>    
        <input type="hidden" id="role" name="roleTarget" value="admin" />   

        <div class="accButton">
            <input type="submit" value="@Localizer["Change role"]" class="button" />
        </div>
        </fieldset>
 }
@section Footer {
    ticket@ticket.by
}
<script>
    $(function () {
        $('#forUser').change(function () {
            document.getElementById('role').value = 'user';
            $.ajax(
                {
                    type: 'GET',
                    url: '@Url.Content("GetAdmins")',
                    success: function (data) {
                        $('#user').replaceWith(data);
                    }
                });
        });
    }
    )

    $(function () {
        $('#forAdmin').change(function () {
            document.getElementById('role').value = 'admin';
            $.ajax(
                {
                    type: 'GET',
                    url: '@Url.Content("GetUsers")',
                    success: function (data) {
                        $('#user').replaceWith(data);
                    }
                });
        });
    }
    )
</script>