TicketsApplication/src/TicketsApplication/Controllers/CitiesController.cs
using AutoMapper;
using BLL.DTO;
using BLL.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TicketsApplication.Models;

namespace TicketsApplication.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CitiesController : Controller
    {
        ICityOption serv;
        public CitiesController(ICityOption serv)
        {
            this.serv = serv;
        }

        #region createCity

        [HttpGet]
        public IActionResult create_city()
        {
            return View();
        }
        [HttpPost]
        public IActionResult create_city(CityVM model)
        {
            if (ModelState.IsValid)
            {
                serv.create_city(Mapper.Map<CityDTO>(model));
                return RedirectToAction("index", "Home");
            }
            return RedirectToAction("createCity");

        }
        #endregion

        #region deleteCity
        [HttpGet]
        public IActionResult delete_city()
        {
            int selectedIndex = 1;
            List<CityVM> citiesL = Mapper.Map<List<CityVM>>(serv.GetCities());
            SelectList cities = new SelectList(citiesL, "ID", "Name", selectedIndex);
            ViewBag.Cities = cities;
            return View();
        }
        [HttpPost]
        public IActionResult delete_city(int CityID)
        {
            serv.delete_city(CityID);
            return RedirectToAction("Index", "Home");
        }
        #endregion

        #region updateCity
        [HttpGet]
        public IActionResult update_city()
        {
            int selectedIndex = 1;
            List<CityVM> citiesL = Mapper.Map<List<CityVM>>(serv.GetCities());
            SelectList cities = new SelectList(citiesL, "ID", "Name", selectedIndex);
            ViewBag.Cities = cities;
            return View();
        }
        [HttpPost]
        public IActionResult update_city_action(int cityID)
        {
            CityVM vm = Mapper.Map<CityVM>(serv.GetCity(cityID));
            return View(vm);
        }

        [HttpPost]
        public IActionResult update_city_result(CityVM model)
        {
            if (ModelState.IsValid)
            {
                serv.update_city(Mapper.Map<CityDTO>(model));
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("updateCityResult");
        }
        #endregion
    }
}

TicketsApplication/src/TicketsApplication/Views/Cities/create_city.cshtml
@model CityVM
@using (Html.BeginForm("create_city", "Cities", FormMethod.Post))
{
    <fieldset>
        <legend>@Localizer["Add city"]</legend>

        <div class="editor-label">
            <p>@Localizer["City name:"]</p>
        </div>
        <div class="editor-field">
            <input type="text" asp-for="Name" />
        </div>
        <div class="accButton">
            <input type="submit" value="@Localizer["Add"]" class="button" />
        </div>
    </fieldset>
}

@section Footer {
    ticket@ticket.by
}

TicketsApplication/src/TicketsApplication/Views/Cities/delete_city.cshtml
@using (Html.BeginForm("delete_city", "Cities", FormMethod.Post))
{
    <div class="editor-label">
        <p>@Localizer["Select a city:"]</p>
    </div>
        <div class="editor-field">
            @Html.DropDownList("CityID", ViewBag.Cities as SelectList)
        </div>
        <div class="accButton">
            <input type="submit" value="@Localizer["Delete"]" class="button" />
        </div>
}

TicketsApplication/src/TicketsApplication/Views/Cities/update_city.cshtml
@using (Html.BeginForm("update_city_action", "Cities", FormMethod.Post))
{
    <div class="editor-label">
        <p>@Localizer["Select a city:"]</p>
    </div>
    <div class="editor-field">
        @Html.DropDownList("CityID", ViewBag.Cities as SelectList)
    </div>
        <div class="accButton">
            <input type="submit" value="@Localizer["Update"]" class="button" />
        </div>
}
@section Footer {
    ticket@ticket.by
}

TicketsApplication/src/TicketsApplication/Views/Cities/update_city_action.cshtml
@model CityVM

@using (Html.BeginForm("update_city_result", "Cities", FormMethod.Post))
{
    <fieldset>
        <legend>@Localizer["Update city"]</legend>

        <div class="editor-label">
            <p>@Localizer["Old name:"] - @Model.Name</p>
            <p>@Localizer["New Name:"]</p>
        </div>
        <div class="editor-field">
            <input type="text" asp-for="Name" />
        </div>
        <input type="hidden" asp-for="ID"/>

        <div class="accButton">
            <input type="submit" value="@Localizer["Update"]" class="button" />
        </div>
    </fieldset>
 }

@section Footer {
    ticket@ticket.by
}